import './globals.css'
import { Lato } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Footer from '@/components/footer/Footer'

const lato = Lato({
  subsets: ['latin'],
  weight: ["100", "300", "400", "700", "900"],
  style: ["normal", "italic"],
  variable: '--font-lato'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={`${lato.variable} font-sans`} lang="en">
      <body className='overflow-y-scroll'>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
